import { describe, expect, test } from "vitest";
import { getNextEvolutionEntry } from "@/lib/pokemon";

const node = (name, evolvesTo = [], minLevels = []) => ({
  species: { name },
  evolves_to: evolvesTo.map((child, idx) => ({
    ...child,
    evolution_details: minLevels[idx] == null ? [] : [{ min_level: minLevels[idx] }],
  })),
});

describe("getNextEvolutionEntry (many blackbox cases)", () => {
  test("returns null when chain is missing / terminal", () => {
    expect(getNextEvolutionEntry(null, "x")).toBe(null);
    expect(getNextEvolutionEntry(node("a", []), "a")).toBe(null);
  });

  test("chooses the lowest minLevel candidate when multiple evolutions exist", () => {
    const chain = node("pichu", [
      node("pikachu"),
      node("raichu"),
      node("alolan-raichu"),
    ], [16, 22, null]);

    const entry = getNextEvolutionEntry(chain, "pichu");
    expect(entry.candidate.species.name).toBe("pikachu");
    expect(entry.minLevel).toBe(16);
  });

  test("deep search finds the correct branch", () => {
    const chain = node("root", [
      node("left", [node("left2")], [30]),
      node("right", [node("target", [node("next")], [42])], [12]),
    ], [null, null]);

    const entry = getNextEvolutionEntry(chain, "target");
    expect(entry.candidate.species.name).toBe("next");
    expect(entry.minLevel).toBe(42);
  });

  test("stress: many autogenerated chains resolve consistently", () => {
    // ~110 cases
    let asserts = 0;
    for (let i = 0; i < 55; i++) {
      const chain = node(`a${i}`, [
        node(`b${i}`),
        node(`c${i}`),
      ], [10 + (i % 5), 30 + (i % 7)]);

      const entry = getNextEvolutionEntry(chain, `a${i}`);
      expect(entry.candidate.species.name).toBe(`b${i}`);
      expect(entry.minLevel).toBe(10 + (i % 5));
      asserts += 2;
    }
    expect(asserts).toBe(110);
  });
});

